import { Assets as PixiAssets, SCALE_MODES, Texture } from "pixi.js"

export const loadAllAssets = async () => {
	const textures = await Promise.all([
		PixiAssets.load("assets/specs-idle.png"),
		PixiAssets.load("assets/specs-mage.png"),
		PixiAssets.load("assets/rune-idle.png"),
		PixiAssets.load("assets/rune-tech.png"),
		PixiAssets.load("assets/shock-orb.png"),
		PixiAssets.load("assets/call-lightning.png"),
		PixiAssets.load("assets/call-lightning-2.png"),
		PixiAssets.load("assets/turret-idle.png"),
		PixiAssets.load("assets/arrow.png"),
		PixiAssets.load("assets/stone-tablet.png"),
		PixiAssets.load("assets/monolith.png"),
		PixiAssets.load("assets/monolith-power.png"),
		PixiAssets.load("assets/beam/BeamShoot1.png"),
		PixiAssets.load("assets/beam/BeamShoot2.png"),
		PixiAssets.load("assets/beam/BeamShoot3.png"),
		PixiAssets.load("assets/beam/BeamShoot4.png"),
		PixiAssets.load("assets/beam/BeamShoot5.png"),
		PixiAssets.load("assets/beam/BeamShoot6.png"),
		PixiAssets.load("assets/beam/BeamShoot7.png"),
		PixiAssets.load("assets/beam/BeamShoot8.png"),
		PixiAssets.load("assets/beam/BeamShoot9.png"),
		PixiAssets.load("assets/beam/BeamShoot10.png"),
		PixiAssets.load("assets/beam/BeamShoot11.png"),
		PixiAssets.load("assets/beam/BeamShoot12.png"),
		PixiAssets.load("assets/beam/BeamShoot13.png"),
		PixiAssets.load("assets/beam/BeamShoot14.png"),
		PixiAssets.load("assets/beam/BeamShoot15.png"),
		PixiAssets.load("assets/beam/BeamShoot16.png"),
		PixiAssets.load("assets/beam/BeamShoot17.png"),
		PixiAssets.load("assets/beam/BeamShoot18.png"),
		PixiAssets.load("assets/beam/BeamShoot19.png"),
		PixiAssets.load("assets/beam/BeamShoot20.png"),
		PixiAssets.load("assets/beam/BeamShoot21.png"),
		PixiAssets.load("assets/beam/BeamShoot22.png"),
		PixiAssets.load("assets/beam/BeamSegment1.png"),
		PixiAssets.load("assets/beam/BeamSegment2.png"),
		PixiAssets.load("assets/beam/BeamCharge1.png"),
		PixiAssets.load("assets/beam/BeamCharge2.png"),
	]) as Texture[]

	textures.forEach((texture) => {
		texture.baseTexture.scaleMode = SCALE_MODES.NEAREST
	})

	const [
		specsIdle,
		specsMage,
		runeIdle,
		runeTech,
		shockOrb,
		callLightning,
		callLightningBolt,
		turretIdle,
		arrow,
		stoneTablet,
		monolith,
		monolithPower,
		beamShoot1,
		beamShoot2,
		beamShoot3,
		beamShoot4,
		beamShoot5,
		beamShoot6,
		beamShoot7,
		beamShoot8,
		beamShoot9,
		beamShoot10,
		beamShoot11,
		beamShoot12,
		beamShoot13,
		beamShoot14,
		beamShoot15,
		beamShoot16,
		beamShoot17,
		beamShoot18,
		beamShoot19,
		beamShoot20,
		beamShoot21,
		beamShoot22,
		beamSegment1,
		beamSegment2,
		beamCharge1,
		beamCharge2,
	] = textures

	return {
		specs: {
			idle: specsIdle,
			alt: specsMage,
		},
		rune: {
			idle: runeIdle,
			alt: runeTech,
		},
		shockOrb: {
			idle: shockOrb,
		},
		callLightning: {
			idle: callLightning,
			bolt: callLightningBolt,
		},
		turret: {
			idle: turretIdle,
			arrow: arrow,
		},
		stoneTablet: {
			long: stoneTablet,
		},
		monolith: {
			idle: monolith,
			alt: monolith,
			power: monolithPower,
		},
		beam: {
			shoot: [
				beamShoot1,
				beamShoot2,
				beamShoot3,
				beamShoot4,
				beamShoot5,
				beamShoot6,
				beamShoot7,
				beamShoot8,
				beamShoot9,
				beamShoot10,
				beamShoot11,
				beamShoot12,
				beamShoot13,
				beamShoot14,
				beamShoot15,
				beamShoot16,
				beamShoot17,
				beamShoot18,
				beamShoot19,
				beamShoot20,
			],
			charge: [beamCharge1, beamCharge2],
			source: [beamShoot21, beamShoot22],
			segment: [beamSegment1, beamSegment2],
			sfx: {
				beam: "assets/beam/beam.ogg",
			},
		},
	}
}

export type Assets = Awaited<ReturnType<typeof loadAllAssets>>
